CREATE DATABASE CODE 
USE CODE

CREATE TABLE GROUPS
(
Id SMALLINT PRIMARY KEY IDENTITY,
No NVARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE STUDENTS 
(
Id SMALLINT PRIMARY KEY IDENTITY,
FullNAME NVARCHAR(30) NOT NULL,
Point TINYINT DEFAULT 0,
GroupId SMALLINT NOT NULL FOREIGN KEY REFERENCES GROUPS(Id)
)
CREATE TABLE EXAMS
(
Id TINYINT PRIMARY KEY IDENTITY,
SubjectName NVARCHAR(30) NOT NULL,
StartDate DATETIME2 NOT NULL ,
EndDate DATETIME2 NOT NULL 
)

CREATE TABLE STUDENTEXAMS
(
StudentId SMALLINT FOREIGN KEY REFERENCES STUDENTS(Id),
ExamId TINYINT FOREIGN KEY REFERENCES EXAMS(Id)
)
ALTER TABLE STUDENTEXAMS
ADD ResultPoint TINYINT CHECK(ResultPoint>=0)

SELECT * FROM STUDENTEXAMS
INSERT INTO STUDENTEXAMS
VALUES
(1,1,100),
(1,2,100),
(1,3,80)


ALTER TABLE STUDENTEXAMS 
ADD CONSTRAINT ForUnique UNIQUE(StudentId,ExamId)




SELECT * FROM STUDENTS
FULL JOIN STUDENTEXAMS ON STUDENTEXAMS.StudentId=STUDENTS.Id


INSERT INTO EXAMS
VALUES
('FrontFinal','2023-06-15','2023-08-10'),
('BackEndFinal','2023-08-10','2023-10-07'),
('Final','2023-10-07','2024-01-07')



INSERT INTO GROUPS
VALUES
('P321'),
('P326'),
('P327'),
('P328')


INSERT INTO STUDENTS
VALUES 
('XALIQ MEMMEDOV',40,1),
('RESAD SADIQOV',50,2),
('QURBAN QURBANLI',60,3),
('IBRAHIM QASIMZADE',70,4),
('MODRIC KAZIMZADE',80,3),
('RESID SERIFOV',100,2)

INSERT INTO EXAMS
VALUES
('YesterdayExam2','2023-04-29','2023-04-30')
INSERT INTO EXAMS
VALUES
('YesterdayExam','2023-04-29','2023-04-30')

UPDATE STUDENTS 
SET Point=0
WHERE Point<>0

 
SELECT *,(SELECT COUNT(Id) FROM STUDENTS WHERE STUDENTS.GroupId=GROUPS.Id) AS StudentCount fROM GROUPS

SELECT * FROM GROUPS 

SELECT S.Id,FullNAME,Point,GroupId,G.No AS GroupNo FROM STUDENTS AS S -- 1
JOIN GROUPS AS G ON S.GroupId=G.Id
WHERE S.GroupId=G.Id


SELECT S.* ,COUNT(Id) AS ExamCount  FROM STUDENTS AS S --2
JOIN STUDENTEXAMS AS SE ON S.Id=SE.StudentId
WHERE SE.StudentId=S.Id
GROUP BY S.Id,S.FullNAME,S.GroupId,S.Point

SELECT * FROM STUDENTS--3
WHERE Point IS NULL

SELECT EXAMS.*,(SELECT COUNT(*) FROM STUDENTEXAMS WHERE STUDENTEXAMS.ExamId=EXAMS.Id ) AS StudentCount  FROM EXAMS --4	
 JOIN STUDENTEXAMS ON STUDENTEXAMS.ExamId=Id
WHERE CONVERT(date,DATEADD(day,0,StartDate))=CONVERT(date,DATEADD(day,-1,GETDATE()))
GROUP BY EXAMS.Id,EXAMS.SubjectName,EXAMS.StartDate,EXAMS.EndDate

SELECT STUDENTEXAMS.*,FullNAME,GroupId FROM STUDENTEXAMS--5
JOIN STUDENTS ON STUDENTS.Id=STUDENTEXAMS.StudentId

UPDATE STUDENTS --UPDATE STUDENT POINT==6
SET POINT=(SELECT AVG(ResultPoint) FROM STUDENTEXAMS WHERE STUDENTEXAMS.StudentId=STUDENTS.Id)




























